#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/runtime:7.0 AS base
WORKDIR /app
COPY Linux/GatewayDocker .
ENTRYPOINT ["dotnet", "JMS.Gateway.dll","-s:share"]